In [1]:
import numpy as np
import math
import random as rd
import matplotlib.pyplot as plt

In [2]:
# define fitness function
def sphere_function(chromosome):
    # evaluate the fitness of a chromosome for the sphere function
    fitness = sum([gene**2 for gene in chromosome])
    return fitness

def rastrigin_function(chromosome):
    # evaluate the fitness of a chromosome for the Rastrigin function
    A = 10
    fitness = A * len(chromosome) + sum([gene**2 - A * math.cos(2 * math.pi * gene) for gene in chromosome])
    return fitness

def satria_function(chromosome):
    A = 10
    fitness = A - (A * sum([gene**2 for gene in chromosome]))
    return fitness

def function_f6(chromosome):
    fitness = sum([math.pow(gene+0.5,2) for gene in chromosome])
    return fitness

def griewank(x):
    d = len(x)
    s = np.sum(x**2)
    p = np.prod(np.cos(x / np.sqrt(np.arange(1, d+1))))
    return 1 + s/4000 - p

In [3]:
# implement GWO for minimize sphere function
def gwo(n_wolfs, dim, n_iterations, xmin, xmax, fitness_function=sphere_function, obj='min'):
    
    isDescendingOrder=True
    if obj=='min':
        isDescendingOrder = False
        
    # Inisialisasi Variabel
    greyWolfs = np.zeros((n_wolfs, dim))
    
    # Tahap 1 inisialisasi Grey Wolf Position
    for i in range(n_wolfs):
        greyWolfs[i] = np.array([rd.uniform(xmin, xmax) for d in range(dim)])
        # apply boundaries
        greyWolfs[i] = np.clip(greyWolfs[i], xmin, xmax)
    
    # GWO
    for iteration in range(n_iterations):
        a = 2 - 2 * iteration / n_iterations
        
        # Tahap 2 Hitung Fitness
        fitness_scores = np.array([fitness_function(wolf) for wolf in greyWolfs])
        if obj == 'min':
            wolf_best_position = greyWolfs[fitness_scores.argmin()][:]
            wolf_best_value = fitness_scores.min()
        else:
            wolf_best_position = greyWolfs[fitness_scores.argmax()][:]
            wolf_best_value = fitness_scores.max()
        print(wolf_best_value)
        
        # Tahap 3 Identifikasi Alpha, Betha, Delta Wolf
        ## Sort greyWolfs berdasarkan nilai fitness teroptimal
        greyWolfsWithFitness = list(zip(greyWolfs, fitness_scores))
        greyWolfsWithFitness.sort(key=lambda x:x[1], reverse=isDescendingOrder)
        greyWolfs = [list(wolf) for wolf, _ in greyWolfsWithFitness]
        sorted_fitness_scores = [fitness for _, fitness in greyWolfsWithFitness]

        ## Tentukan alpha, betha, delta
        alphaWolf = greyWolfs[0]
        bethaWolf = greyWolfs[1]
        deltaWolf = greyWolfs[2]
        
        # Tahap 4 Updating position grey wolf
        for idx_wolf, wolf in enumerate(greyWolfs):
            ## hitung Komponen Alpha
            A1 = 2 * a * np.random.rand(dim) - a
            C1 = 2 * np.random.rand(dim)
            D_alpha = np.abs(C1 * alphaWolf - wolf)
            X1 = alphaWolf - (A1*D_alpha)
            
            ## hitung komponen Betha
            A2 = 2 * a * np.random.rand(dim) - a
            C2 = 2 * np.random.rand(dim)
            D_betha = np.abs(C2 * bethaWolf - wolf)
            X2 = bethaWolf - (A2*D_betha)
            
            ## hitung komponen Delta
            A3 = 2 * a * np.random.rand(dim) - a
            C3 = 2 * np.random.rand(dim)
            D_deltha = np.abs(C3 * deltaWolf - wolf)
            X3 = deltaWolf - (A3*D_deltha)
            
            ## update posisi Wolf ke-i
            greyWolfs[idx_wolf] = (X1+X2+X3)/3
            greyWolfs[idx_wolf] = np.clip(greyWolfs[idx_wolf], xmin, xmax)

In [4]:
# def grey_wolf_optimization(n_wolfs, dim, n_iterations, xmin, xmax, fitness_function=sphere_function, obj='min'):
    
#     def distance_vector(vector1, vector2, weight_vector1=1):
#         return np.sum((weight_vector1* vector1) - vector2)
    
#     # Function Tahap 2
#     def evaluateFitness(greyWolfs):
#         fitness_scores = np.array([1/fitness_function(wolf) for wolf in greyWolfs])
#         ## tentukan wolf dengan fitness teroptimal sebagai prey
#         if obj == 'min':
#             wolf_best_position = greyWolfs[fitness_scores.argmin()][:]
#             wolf_best_value = fitness_scores.min()
#         else:
#             wolf_best_position = greyWolfs[fitness_scores.argmax()][:]
#             wolf_best_value = fitness_scores.max()
#         return fitness_scores, wolf_best_position, wolf_best_value
            
#     # Function Tahap 3
#     def findAlphaBethaDelthaWolf(greyWolfs, fitness_scores, isDescendingOrder):
#         ## Sort greyWolfs berdasarkan nilai fitness teroptimal
#         greyWolfsWithFitness = list(zip(greyWolfs, fitness_scores))
#         greyWolfsWithFitness.sort(key=lambda x:x[1], reverse=isDescendingOrder)
#         greyWolfs = [list(wolf) for wolf, _ in greyWolfsWithFitness]
#         sorted_fitness_scores = [fitness for _, fitness in greyWolfsWithFitness]

#         ## Tentukan alpha, betha, delta
#         alphaWolf = greyWolfs[0]
#         bethaWolf = greyWolfs[1]
#         deltaWolf = greyWolfs[2]
#         return greyWolfs, alphaWolf, bethaWolf, deltaWolf
    
#     isDescendingOrder=True
#     if obj=='min':
#         isDescendingOrder = False
        
#     # Tahap 1: Inisialisasi posisi serigala secara acak dalam ruang solusi
#     greyWolfs = np.zeros((n_wolfs, dim))
#     for i in range(n_wolfs):
#         greyWolfs[i] = np.array([rd.uniform(xmin, xmax) for d in range(dim)])
    
#     # Check the greyWolfs positions boundaries
#     for idx_wolf in range(n_wolfs):
#         greyWolfs[idx_wolf] = np.clip(greyWolfs[idx_wolf], xmin, xmax)
        
#     ## inisialisasi parameter transisi a
#     a = 0
    
#     # Tahap 2: Evaluasi fitness untuk setiap serigala
#     fitness_scores, wolf_best_position, wolf_best_value = evaluateFitness(greyWolfs)

    
#     """
#     Hierarki Serigala Abu-abu
#     - Serigala alpha:  tingkatan tertinggi dalam kawanan serigala (1st best solution) 
#     - Serigala betha: pembantu serigala alpha dalam mengambil keputusan (2nd best solution)
#     - Serigala delta: Serigala ini tunduk pada alpha dan betha, namun diatas omega (3rd best solution)
#     - Serigala omega: Tingkat terendah dari kawanan serigala. Serigala ini bukan individu yang penting dalam kawanan
#     """
#     # Tahap 3: Tentukan serigala alpha, betha, delta dari nilai fitness
#     greyWolfs, alphaWolf, bethaWolf, deltaWolf = findAlphaBethaDelthaWolf(greyWolfs, fitness_scores, isDescendingOrder)
    
#     # Tahap 4: Grey Wolf Optimization
#     for iteration in range(n_iterations):
#         print(f'BEST VALUE = {wolf_best_value}')
#         # Hitung nilai a
#         a = 2 - 2 * iteration / n_iterations
        
#         # Tahap 5: Update posisi dari setiap serigala
#         for idx_wolf, wolf in enumerate(greyWolfs):
#             ## hitung Komponen Alpha
#             r1 = rd.uniform(0,1)
#             r2 = rd.uniform(0,1)
#             A1 = np.array([(2*a*r1 - a) for i in range(dim)])
#             C1 = np.array([(2*r2) for i in range(dim)])
            
#             dist_alpha = distance_vector(alphaWolf, wolf, C1)
#             X1 = alphaWolf - (A1*dist_alpha)
            
#             ## hitung komponen Betha
#             r1 = rd.uniform(0,1)
#             r2 = rd.uniform(0,1)
#             A2 = np.array([(2*a*r1 - a) for i in range(dim)])
#             C2 = np.array([(2*r2) for i in range(dim)])
            
#             dist_betha = distance_vector(bethaWolf, wolf, C2)
#             X2 = bethaWolf - (A2*dist_betha)
            
#             ## hitung komponen Delta
#             r1 = rd.uniform(0,1)
#             r2 = rd.uniform(0,1)
#             A3 = np.array([(2*a*r1 - a) for i in range(dim)])
#             C3 = np.array([(2*r2) for i in range(dim)])
            
#             dist_deltha = distance_vector(deltaWolf, wolf, C3)
#             X3 = deltaWolf - (A3*dist_deltha)
            
#             ## update posisi Wolf ke-i
#             greyWolfs[idx_wolf] = (X1+X2+X3)/3
        
#         # Tahap 6: Update parameter transisi a
#         a =  2 * (1-(iteration/n_iterations))
        
#         # Tahap 7: Evaluasi fitness dari sekawanan serigala
#         ## Check the greyWolfs positions boundaries
#         for idx_wolf in range(n_wolfs):
#             greyWolfs[idx_wolf] = np.clip(greyWolfs[idx_wolf], xmin, xmax)
#         fitness_scores, wolf_best_position, wolf_best_value = evaluateFitness(greyWolfs)
        
#         # Tahap 8: Update Serigala Alpha, Betha, Delta
#         greyWolfs, alphaWolf, bethaWolf, deltaWolf = findAlphaBethaDelthaWolf(greyWolfs, fitness_scores, isDescendingOrder)
        

In [16]:
n_wolfs = 100
dim = 5
n_iterations = 300
xmin = -600
xmax = 600
fitness_function = rastrigin_function
obj='max'

In [17]:
best_solution = gwo(n_wolfs, dim, n_iterations, xmin, xmax, fitness_function, obj)

1259977.3668272705
1399289.5273782832
1684519.9996109968
1767048.2503074096
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1798296.4626316102
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1796555.046715232
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1770185.5184830886
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1774739.6187953472
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1780155.3808921773
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0
1800000.0


In [7]:
best_solution

In [8]:
x = np.array([1,2,3])
y = np.array([2,3,4])
x-y

array([-1, -1, -1])

In [9]:
np.abs(x-y)

array([1, 1, 1])

In [10]:
np.random.rand(dim)

array([0.68710274, 0.18886223, 0.94462038, 0.95489424, 0.1222037 ])